### ISSUE TITLE
Out-of-bounds issue?

### ISSUE THREAD

**Issue by AeriaVelocity** [Phate6660/gzdoom-discordrpc#4]
I get this error whenever I use it with GZDoom:
```
> gzdoom-discordrpc.exe gzdoom
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', src\main.rs:35:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Phate6660** [comment]
Hmm, I see the issue. It must be picking up the wrong window title and attempting but failing to split it.

Do you have any windows in the name that contain "doom" in the title?

I thought I added regex to not grab firefox and palemoon windows, but I need to add more exclusions.

**Comment by AeriaVelocity** [comment]
Nope, GZDoom was the only one at the time.
I also use a mod that changes the window title, so I'll try running it unmodded.

**Comment by AeriaVelocity** [comment]
Yep, GZDoom unmodded doesn't work either, and I have no other windows open except Firefox and Command Prompt.

**Comment by AeriaVelocity** [comment]
Wait, no, never mind. GZDoom works unmodded, just not *with* the mod I was using at the time.

**Comment by Phate6660** [comment]
Yeah, that'd be the issue. The program expects the title to be in the format `level - game`.

I should add to the README that this is incompatible with anything that changes the window title from that format.

**Comment by AeriaVelocity** [comment]
Right, thanks.
